"""Local banking knowledge base used by the demo assistant."""

# Each entry contains search phrases and a clear, customer-safe response.
FAQS = [
 ("transfer money send funds beneficiary neft rtgs imps", "To transfer money, open Payments, choose or add a beneficiary, enter the amount and confirm using your secure PIN or OTP. IMPS is usually instant; NEFT and RTGS follow banking settlement windows."),
 ("upi payment pay scan qr", "Open Payments, select UPI, enter a UPI ID or scan a QR code, check the recipient name, and confirm with your UPI PIN."),
 ("upi limit daily", "UPI limits vary by bank and transaction type. Your available limit is shown before confirmation in the payment flow."),
 ("upi pending pending payment", "A pending UPI payment usually resolves automatically. Please do not retry immediately; check the transaction status and contact support if it remains pending after 24 hours."),
 ("upi failed failure", "If a UPI payment fails, the amount is generally not debited. If it was debited, it is normally reversed automatically. Keep the reference number for support."),
 ("upi pin change reset", "You can reset your UPI PIN from UPI settings using your linked debit-card details and an OTP. Never share your UPI PIN with anyone."),
 ("open account savings new account", "You can open a savings account online with PAN, Aadhaar, a mobile number and a quick video KYC. Go to Accounts to begin."),
 ("minimum balance savings", "Minimum-balance rules depend on your account variant and location. Check your account details or fee schedule for the exact requirement."),
 ("account number ifsc", "Your account number and IFSC are available in Account details. Share them only when you trust the recipient and need to receive funds."),
 ("account statement download", "Open Accounts and choose Statements to select a date range and download or email your account statement."),
 ("mini statement last transactions", "Your dashboard shows recent transactions. Use Statements for a longer date range and downloadable record."),
 ("balance available current", "Your available balance is displayed on the dashboard. It may differ from the ledger balance while a transaction is pending."),
 ("cash deposit", "You can deposit cash at a supported branch or cash-deposit machine. Keep the receipt until the credit appears in your account."),
 ("cash withdrawal atm", "Use your debit card and PIN at an ATM to withdraw cash. Review the displayed fee before confirming if you use another bank's ATM."),
 ("cash withdrawal limit atm limit", "Your daily ATM withdrawal limit depends on the card type. You can view or adjust eligible card limits in Card controls."),
 ("cheque book", "Request a cheque book from Accounts > Service requests. It will be delivered to your registered address when eligible."),
 ("stop cheque payment", "You can request a stop payment for an unused cheque from Service requests. Submit it promptly; fees and eligibility may apply."),
 ("close account", "To close an account, clear any dues, transfer the remaining balance and submit a closure request through support or your branch."),
 ("nominee add change", "You can add or update a nominee in Account settings. Nominee information helps with settlement in unforeseen circumstances."),
 ("address change update", "Update your address from Profile > Personal details. You may be asked to upload a valid proof of address."),
 ("mobile number change", "To change a registered mobile number, use Profile > Personal details or visit a branch if additional verification is required."),
 ("email change", "Update your email in Profile after verifying it with an OTP. Your registered email receives statements and security alerts."),
 ("pan update", "You can submit PAN details through Profile or KYC updates. Make sure the name and date of birth match your official records."),
 ("kyc update verify", "KYC can be completed online using PAN, Aadhaar and video verification where available. Keep your documents ready and follow the on-screen steps."),
 ("video kyc", "During video KYC, use a well-lit place, stable internet and original identity documents. A bank representative will guide you through verification."),
 ("forgot password reset login", "Select Forgot password on the sign-in page. After OTP verification, you can create a new secure password."),
 ("change password", "Go to Settings > Security > Change password. Use a unique, strong password and do not reuse old passwords."),
 ("login locked account", "For security, repeated incorrect attempts can temporarily lock access. Use password reset or contact support after identity verification."),
 ("otp not received", "Check that your registered mobile has signal, wait a moment and request a new OTP. Never disclose an OTP to anyone, including bank staff."),
 ("fraud scam phishing suspicious", "Do not share passwords, OTPs, CVV or PINs. Stop interacting with the caller or link, block your card if needed, and report the incident immediately."),
 ("card lost stolen block", "Immediately block a lost or stolen card from Cards > Card controls, then contact 24×7 support to arrange a replacement."),
 ("debit card apply", "You can request an eligible debit card from Cards. Delivery and activation instructions will be sent to your registered contact details."),
 ("debit card activate", "Activate your new debit card through Card controls or an ATM, then set a PIN. Do not write the PIN on the card."),
 ("debit card pin change", "Change or set your debit-card PIN from Card controls or an ATM after identity verification."),
 ("debit card international", "Enable international usage only when needed through Card controls. Turn it off again after travel for extra security."),
 ("debit card contactless tap", "Contactless payments work by tapping the card at supported terminals. You may be asked for your PIN above regulatory limits."),
 ("credit card apply eligibility", "Credit-card eligibility depends on income, credit history and internal policy. You can check available card offers in Cards."),
 ("credit card bill payment", "Pay your credit-card bill from Cards > Pay bill before the due date. Paying the total amount due avoids most interest charges."),
 ("credit card due date minimum due", "The minimum amount due prevents late-payment status but interest may apply to the remaining balance. Paying the full amount is best whenever possible."),
 ("credit card limit increase", "You can request a credit-limit review from Card details. Approval depends on account history and eligibility."),
 ("credit card cash advance", "A cash advance can be withdrawn using your credit card but generally has fees and interest from the withdrawal date. Use it only for emergencies."),
 ("credit card reward points", "View reward points and eligible redemption options in Cards > Rewards. Terms, expiry and redemption values can vary by program."),
 ("credit card charge dispute", "For an unrecognized card transaction, freeze the card if needed and raise a dispute from the transaction detail as soon as possible."),
 ("card replacement damaged", "Request a replacement for a damaged card through Card controls. Your existing card may be disabled when the replacement is issued."),
 ("loan apply personal home car", "You can explore personal, home and vehicle loan offers in Loans. Final approval is based on eligibility, documents and credit assessment."),
 ("loan emi calculator", "EMI depends on loan amount, interest rate and tenure. Use the EMI calculator in your dashboard for an estimated monthly instalment."),
 ("loan emi missed overdue", "If you may miss an EMI, contact the loan team early. Late charges and credit-report impact may apply to overdue payments."),
 ("loan prepayment foreclosure", "Prepayment or foreclosure terms depend on your loan agreement. Check the loan details for eligible amount, charges and instructions."),
 ("loan interest rate", "Loan rates vary with product, profile, tenure and market conditions. The final rate is shown in your approved loan offer."),
 ("loan status application", "Track your loan application from Loans > Applications. We may request documents or updates during verification."),
 ("home loan documents", "Home-loan documents commonly include identity, address, income, bank statements and property papers. Your loan checklist will show exact requirements."),
 ("fixed deposit fd open", "A fixed deposit offers a fixed interest rate for a selected tenure. You can open one in Investments after reviewing rate and premature-withdrawal terms."),
 ("fixed deposit fd interest", "FD interest varies by tenure, deposit amount and customer category. The applicable rate is shown before you confirm your deposit."),
 ("fixed deposit premature close", "You may close an FD early, subject to product rules and possible reduced interest or a penalty. Review the shown amount before confirming."),
 ("recurring deposit rd", "A recurring deposit lets you invest a fixed amount each month for a chosen tenure. You can set it up from Investments."),
 ("interest certificate tax", "Interest certificates and tax documents can be downloaded from Statements or Tax documents after the relevant period closes."),
 ("tds tax deducted", "TDS may be deducted on eligible interest income according to tax rules and submitted declarations. Consult a tax professional for personal advice."),
 ("mutual fund investment", "Mutual-fund investments are subject to market risk. Review the scheme information, risk level and suitability before investing."),
 ("demat trading", "For demat or trading services, complete the separate onboarding and KYC steps. Investments can rise or fall in value."),
 ("international transfer foreign exchange forex", "International transfers require additional beneficiary and purpose information, and exchange rates and fees apply. Check the quoted rate before confirmation."),
 ("remittance receive money abroad", "To receive an overseas remittance, provide the sender with your account details and any required bank identifiers. Compliance checks may apply."),
 ("neft timing", "NEFT is available in scheduled settlement cycles and may be available around the clock depending on bank policy. The app will show the estimated delivery time."),
 ("rtgs timing", "RTGS is intended for high-value transfers and follows applicable minimum amount and settlement rules. The transfer screen shows availability."),
 ("imps timing", "IMPS is generally an immediate, 24×7 interbank transfer option, subject to bank availability and transaction limits."),
 ("beneficiary add cooling period", "For safety, a new beneficiary may have a cooling period or lower initial transfer limit. The app will display any restriction clearly."),
 ("beneficiary delete", "Go to Payments > Beneficiaries, select the beneficiary and choose Remove. Verify the name carefully before managing beneficiaries."),
 ("wrong transfer sent", "Contact support immediately with the transaction reference. Recovery depends on the recipient bank and consent; the bank cannot guarantee reversal."),
 ("transaction pending", "Pending transactions are awaiting final confirmation. Avoid duplicate payments and allow the stated processing time before reporting it."),
 ("transaction reversed refund", "A reversal means a completed or pending debit was returned to your account. Refund timing depends on the merchant and payment method."),
 ("merchant refund", "Merchant refunds are initiated by the merchant and can take several business days to appear. Keep the merchant confirmation and transaction reference."),
 ("chargeback", "A chargeback is a formal dispute for eligible card transactions. Raise it promptly and provide any requested proof or merchant communication."),
 ("bank charges fees", "Applicable charges are listed in the schedule of charges for your account and card type. Transaction details may also show the specific fee."),
 ("sms charges", "SMS-alert fees, if applicable, are shown in your account's schedule of charges and statement."),
 ("branch locator nearby", "Use the Branch locator feature to find nearby branches, ATMs, operating hours and contact details."),
 ("customer care support contact", "You can reach support through the in-app Help section or the official number on our website. Use only verified bank contact channels."),
 ("complaint grievance", "Raise a complaint from Help > Support and save the ticket number. You can track its status and escalate it through the grievance process if needed."),
 ("bank holiday", "Branch holidays vary by state and city. Digital banking services may still be available; check the Branch locator for local hours."),
 ("notification alerts", "Manage transaction, balance and promotional alerts from Settings > Notifications. Keep security alerts enabled."),
 ("spending limit card controls", "You can view eligible transaction limits and usage controls under Cards > Card controls. Lower limits can improve security."),
 ("freeze unfreeze card", "Freeze a card instantly from Card controls if you cannot locate it. Unfreeze only after you are certain it is safe."),
 ("credit score cibil", "Your credit score reflects credit history reported by lenders. Pay dues on time and avoid excessive credit applications to support healthy credit behaviour."),
 ("joint account", "Joint-account availability and operating instructions depend on the account type. Contact support or a branch to open or update one."),
 ("salary account", "A salary account may include benefits based on your employer arrangement. Check the account details for eligibility and features."),
 ("senior citizen", "Senior citizens may be eligible for specific deposit rates or service options. Review product terms or contact support for current eligibility."),
 ("minor account child", "Minor accounts require a guardian and supporting documents. Product rules change when the account holder reaches the applicable age."),
 ("bank locker", "Locker availability, rent and allotment vary by branch. Contact your preferred branch to register interest and learn the process."),
 ("nri account nre nro", "NRI account options such as NRE and NRO have different repatriation and tax treatment. Use the NRI section or seek professional advice for your situation."),
 ("aadhaar link", "Link or update Aadhaar only through secure, official banking flows. We will never ask you to share an OTP over a call or chat."),
 ("qr scanner", "Use the in-app QR scanner only after verifying the merchant name and amount. A QR code should never be scanned to receive money from someone."),
 ("voice banking", "Voice assistance can help with navigation, but you should never speak or provide passwords, PINs, CVV or OTPs."),
 ("digital banking secure", "Use a strong password, keep your app updated, enable alerts, and access banking only from trusted devices and networks."),
 ("device change new phone", "When using a new device, sign in with your credentials and complete the device verification. Remove old devices from Settings if available."),
 ("logout session", "Always sign out after banking on a shared device. For security, the app may automatically end inactive sessions."),
 ("two factor authentication 2fa", "Two-factor authentication combines your password with an OTP or device confirmation. Keep your registered phone secure."),
 ("interest calculator savings", "Savings interest is calculated according to your account terms and balance method. The Interest calculator provides an estimate only."),
 ("currency exchange rate", "Exchange rates change throughout the day. The final rate, applicable taxes and fees are displayed before you confirm a foreign-currency transaction."),
 ("cashback offer coupon", "Cashback and offers have specific eligibility, spend, merchant and expiry conditions. Check the offer details before making a purchase."),
 ("insurance bank", "Insurance products are offered subject to policy terms, underwriting and eligibility. Read the brochure and policy wording carefully."),
 ("hindi पैसे भेजना transfer", "पैसे भेजने के लिए Payments में जाएँ, लाभार्थी चुनें, राशि भरें और सुरक्षित PIN या OTP से पुष्टि करें।"),
 ("hindi खाता खोलना account", "नया बचत खाता खोलने के लिए PAN, Aadhaar, मोबाइल नंबर और वीडियो KYC की आवश्यकता हो सकती है।"),
 ("hindi बैलेंस balance", "आपका उपलब्ध बैलेंस डैशबोर्ड पर दिखता है। लंबित लेनदेन के कारण यह कभी-कभी अलग हो सकता है।"),
 ("hindi लोन emi loan", "EMI लोन राशि, ब्याज दर और अवधि पर निर्भर करती है। डैशबोर्ड का EMI कैलकुलेटर अनुमान दे सकता है।"),
 ("hindi कार्ड खो गया lost", "कार्ड खो जाने पर तुरंत Card controls से ब्लॉक करें और आधिकारिक सहायता चैनल से संपर्क करें।"),
 ("hindi upi पिन", "अपना UPI PIN या OTP किसी के साथ साझा न करें। PIN बदलने के लिए UPI settings का उपयोग करें।"),
 ("hindi फ्रॉड fraud", "यदि धोखाधड़ी का संदेह हो, तो OTP, PIN या CVV साझा न करें। तुरंत कार्ड ब्लॉक करें और बैंक को रिपोर्ट करें।"),
]

def answer(question: str) -> str:
    text = question.lower().strip()
    best, score = None, 0
    for keywords, response in FAQS:
        matches = sum(1 for word in keywords.lower().split() if len(word) > 1 and word in text)
        if matches > score:
            best, score = response, matches
    if best:
        return best
    return "I can help with accounts, cards, transfers, UPI, loans, deposits, security and payments. Could you share a little more about what you need?"
